import { LogInForm } from '@/src/components/LogInForm'
import { SignUpForm } from '@/src/components/SignUpForm'
import supabase from '@/src/supabase';
import Head from 'next/head'
import React from 'react'
import Image from 'next/image';


export default function Home() {
  const [user, setUser] = React.useState<any|undefined>(undefined);
  const checkUserAuth = async () => 
  {
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      setUser(user);
    }
  }

  React.useEffect(() => {
    checkUserAuth()
  }, []);

  const handleUploadImage = async (event: React.ChangeEvent<HTMLInputElement>) => 
  {
    if (user === null) return;
    const file: File|null = event.target.files === null ?
                              null : event.target.files[0];
    if (!file) return;

    try {
      const res = await supabase.storage.from('avatars').upload(
        `${user.id}-${Date.now()}`, file
      );
      console.log("Res: ", res.data?.path);
    } catch (err) {
      console.error("Error uploading the image to supabase. ", err);
    }
    
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpForm />
      <LogInForm />
      {
        user !== undefined ?
          <>
            <Image alt='img' src={"https://jqsgcqrnrugsklqsnydr.supabase.co/storage/v1/object/public/avatars/bdfbf86c-e442-473b-be05-8b0fd0260fed-1696356493693"} width={100} height={100}/>
            <h3>Upload your photo.</h3>
            <input type='file' name='img' accept='image/*' onChange={(e) => handleUploadImage(e)} />
          </> : <p>User not authenticated.</p>
      }
    </>
  );
}
